const RC = require('rc')('IOP', require('../../config/default.json'))

module.exports = {
  ENDPOINT_SOURCE_URL: RC.ENDPOINT_SOURCE_URL,
  ROUTING_ENDPOINT: RC.ROUTING_ENDPOINT,
  ENDPOINT_CACHE_CONFIG: RC.ENDPOINT_CACHE_CONFIG,
  PROVISIONED_PARTIES: RC.PROVISIONED_PARTIES,
  ACCOUNT_LOOKUP_DATA: RC.ACCOUNT_LOOKUP_DATA,
  DATABASE_URI: RC.DATABASE_URI
}
